[node]
# working_dir = "$PATH_TO_YOUR_CHAINSTATE"
# seed = "$YOUR_BTC_PRIVATE_KEY"
# local_peer_seed = "$SOME_OTHER_PRIVATE_KEY"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
prometheus_bind = "0.0.0.0:9153"
mine_microblocks = true
wait_time_for_microblocks = 0
bootstrap_node = "027e929237cc4c12980b109bd3180ca591f3b72896b6e3716f5d1dce0a5bdd2dc4@next.stacks.org:20444"
name = "xenon-node-2.1"

[burnchain]
# NOTE: you will need to run your own Bitcoin testnet node to mine!
chain = "bitcoin"
mode = "xenon"
peer_host = "bitcoin.testnet.stacks.org"
username = "stacks"
password = "foundation"
rpc_port = 18332
peer_port = 18333
pox_2_activation = 2406590
poll_time_secs = 2
magic_bytes = "21"
burn_fee_cap = 10000
satoshis_per_byte = 10
rbf_fee_increment = 5
max_rbf = 150

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 2000000

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 2104380

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 2406000

[[ustx_balance]]
address = "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
amount = 10000000000000000

[[ustx_balance]]
address = "ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF"
amount = 10000000000000000

[[ustx_balance]]
address = "ST221Z6TDTC5E0BYR2V624Q2ST6R0Q71T78WTAX6H"
amount = 10000000000000000

[[ustx_balance]]
address = "ST2TFVBMRPS5SSNP98DQKQ5JNB2B6NZM91C4K3P7B"
amount = 10000000000000000
